##использовался для инициализации db h2

CREATE TABLE USERS(USERID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	FIRSTNAME VARCHAR(255),
	LASTNAME VARCHAR(255),
	CUSTOMERPHONE VARCHAR(255),
	SHIPPINGADDRESS VARCHAR(255),
	BALANCE DOUBLE,
	DISCOUNT DOUBLE,
	ROLE VARCHAR(255)
);


CREATE TABLE CUSTOMERORDER(CUSTOMERORDERID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STATUS VARCHAR(255),
	TOTAL DOUBLE,
	USERID INT,
	OPENDATE DATE,
	CLOSEDATE DATE,
	CONSTRAINT FKUSERID FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);

CREATE TABLE ORDERITEM(ORDERITEMID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	QUANTITY INT,
	PRICE DOUBLE,
	PRODUCTID VARCHAR(255),
	PRODUCTNAME VARCHAR(255),
	CUSTOMERORDERID INT,
	CONSTRAINT FKCUSTOMERORDERID FOREIGN KEY(CUSTOMERORDERID) REFERENCES CUSTOMERORDER(CUSTOMERORDERID)
);


CREATE TABLE PRODUCT(PRODUCTID VARCHAR(255) PRIMARY KEY,
	NAME VARCHAR(255),
	PHOTO VARCHAR(255),
	PRICE DOUBLE,
	STOREQTY INT
);


INSERT INTO PRODUCT VALUES
('p01', 'tulip', 'tulip.jpg', 20, 10000),
('p02', 'rose', 'rose.jpeg', 21, 10000),
('p03', 'chamomile', 'chamomile.jpg', 22, 10000);

INSERT INTO USERS VALUES
(11, 'admin', 'admin123', 'admin', 'admin', '+79991112233', 'City, Street, ect', 2000, 3, 'ADMIN'),
(12, 'user', '54321', 'user', 'user', '+79991112233', 'City, Street, ect', 2000, 3, 'USER');